name: CI

on:
  push:
    branches:
      - main
  pull_request:

x-setup: &setup
  - uses: actions/checkout@v4
  - run: |
      BRANCH="${{ github.head_ref || github.ref_name }}"
      git clone https://github.com/extrabits-io/p2p-relay.git ../p2p-relay
      git -C ../p2p-relay checkout "$BRANCH" || true
      git clone https://github.com/extrabits-io/p2p-app-host.git ../p2p-app-host
      git -C ../p2p-app-host checkout "$BRANCH" || true
  - run: cp workspace/Cargo.* ..

jobs:
  rust:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - *setup
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: cargo build --all-features
      - run: cargo test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - *setup
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - *setup
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D warnings
